name: Github Actions Demo

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule: 
    - cron: "15 4 * * *" #to be fixed
  workflow_dispatch:
    inputs:
      logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
              - info
              - warning
              - debug
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Print out trigger name
        run: echo trigger name 
      - name: Print out branch name
        run: echo branch name 
  


  
  
